"""Write the exact numbers a figure draws to a sidecar CSV next to the PDF.

Why this exists: `artifact/verify_figs.py` originally compared only the text
layer of the reproduced and published PDFs. For the result figures (Figures 9,
10a, 10b, 12, 15) that layer holds axis ticks, legend strings and nothing else --
every plotted value is a bar height or a line vertex, which is vector geometry,
not text. A reviewer could therefore change a cost in `research/data/*.csv` by
30%, replot, and still be told MATCH.

Each plotting script now calls `write_values()` with the aggregate it is about to
draw, producing `<figure>.values.csv` beside `<figure>.pdf`. `verify_figs.py`
diffs those numerically against the reference copies under `paper_figs/values/`.

What that check does and does not establish, stated precisely:

  * It does establish that the reproduced figure draws the same numbers as the
    figures in the paper, to a relative tolerance, and it fails loudly if the
    shipped result CSVs or the aggregation change.
  * It does not independently re-derive those numbers. The reference sidecars
    were generated by these same scripts from the shipped `research/data/*.csv`,
    which is the data the published figures were made from. Re-deriving the CSVs
    means re-running the simulation sweeps -- see the `--config` commands in
    README.md, which is the check that does not rely on the shipped results.
"""

from __future__ import annotations

from pathlib import Path
from typing import Iterable, Sequence

import pandas as pd

SIDECAR_SUFFIX = ".values.csv"

# Enough digits to catch any real change, few enough that trailing float noise
# does not make two runs of the same script disagree textually.
FLOAT_FORMAT = "%.6f"


def warn_missing_strategies(
    present: Iterable[str], expected: Sequence[str], context: str = ""
) -> list[str]:
    """Print a loud warning for expected strategies absent from the input.

    The plotting scripts drop unknown names silently, so a sweep re-run under a
    differently-named baseline (e.g. `multi_region_oracle_dp_safety_net` instead
    of `multi_region_oracle_dp`) used to lose the Optimal reference line with no
    indication that anything was missing.
    """
    present_set = set(present)
    missing = [s for s in expected if s not in present_set]
    if missing:
        where = f" in {context}" if context else ""
        print(
            f"WARNING: {len(missing)} expected strategy/strategies not found{where} "
            f"and will be absent from the figure: {', '.join(missing)}"
        )
    return missing


def sidecar_path(output_path: Path | str) -> Path:
    """`outputs/figures/foo.pdf` -> `outputs/figures/foo.values.csv`."""
    p = Path(output_path)
    return p.with_name(p.stem + SIDECAR_SUFFIX)


# The sidecars are read against the paper, so they carry the paper's names for the
# policies rather than the registry keys the simulator uses internally.
PAPER_LABELS = {
    "unified_cost_model_risk": "SkyNomad",
    "unified_cost_model_rate_ratio": "SkyNomad",
    "unified_cost_model_rate_past": "SkyNomad",
    "unified_cost_model_oracle": "SkyNomad(o)",
    "multi_region_oracle_dp": "Optimal",
    "multi_region_rc_cr_threshold_eager_failover": "UP(S)",
    "multi_region_availability_probe_simple": "UP(A)",
    "multi_region_probe_cost_ratio": "UP(AP)",
    "rc_cr_threshold": "UP",
}


def paper_label(name: str) -> str:
    """Registry key -> the name the paper uses for that policy."""
    return PAPER_LABELS.get(name, name)


def write_values(
    output_path: Path | str,
    df: pd.DataFrame,
    columns: Sequence[str],
    sort_by: Iterable[str] | None = None,
) -> Path:
    """Write `df[columns]` to the sidecar for `output_path` and return its path.

    Rows are sorted so two runs produce byte-identical files regardless of
    groupby ordering.
    """
    missing = [c for c in columns if c not in df.columns]
    if missing:
        raise KeyError(f"figure values missing column(s) {missing}; have {list(df.columns)}")

    out = df.loc[:, list(columns)].copy()
    if "strategy" in out.columns:
        out["strategy"] = out["strategy"].map(paper_label)
    by = list(sort_by) if sort_by is not None else [c for c in columns[:2]]
    out = out.sort_values(by=by, kind="mergesort").reset_index(drop=True)

    path = sidecar_path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    out.to_csv(path, index=False, float_format=FLOAT_FORMAT)
    print(f"Saved: {path}")
    return path
